name: Coding Standards

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  coding-standards:
    if: github.event.pull_request.draft == false
    uses: alleyinteractive/.github/.github/workflows/php-coding-standards.yml@main
