name: Tests

on:
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.0, 7.4 ]
        wp_version: [ "latest" ]
        can_fail: [ false ]
        multisite: [ 0,1 ]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    continue-on-error: ${{ matrix.can_fail }}

    name: WordPress ${{ matrix.wp_version }} @ PHP ${{ matrix.php }} (WP_MULTISITE=${{ matrix.multisite }})
    env:
      CACHEDIR: /tmp
      WP_CORE_DIR: /tmp/wordpress
      WP_VERSION: ${{ matrix.wp_version }}
      WP_MULTISITE: ${{ matrix.multisite }}
      WP_DB_HOST: 127.0.0.1
      WP_DB_USER: root
      WP_DB_PASSWORD: '""'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, mysqli, curl, dom, exif, fileinfo, hash, imagick, mbstring, openssl, pcre, xml, zip
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install

      - name: Run PHPUnit
        run: composer run-script phpunit
